//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace BookCreator.ru_morpher_api {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://morpher.ru/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Credentials credentialsValueField;
        
        private System.Threading.SendOrPostCallback GetAdjectivesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitCorrectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeclensionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetXmlUkrOperationCompleted;
        
        private System.Threading.SendOrPostCallback PropisUkrOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDailyQueryLimitOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateClientIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback PropisOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::BookCreator.Properties.Settings.Default.BookCreator_ru_morpher_api_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Credentials CredentialsValue {
            get {
                return this.credentialsValueField;
            }
            set {
                this.credentialsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAdjectivesCompletedEventHandler GetAdjectivesCompleted;
        
        /// <remarks/>
        public event SubmitCorrectionCompletedEventHandler SubmitCorrectionCompleted;
        
        /// <remarks/>
        public event GetAccountStatusCompletedEventHandler GetAccountStatusCompleted;
        
        /// <remarks/>
        public event GetDeclensionCompletedEventHandler GetDeclensionCompleted;
        
        /// <remarks/>
        public event GetXmlUkrCompletedEventHandler GetXmlUkrCompleted;
        
        /// <remarks/>
        public event PropisUkrCompletedEventHandler PropisUkrCompleted;
        
        /// <remarks/>
        public event GetDailyQueryLimitCompletedEventHandler GetDailyQueryLimitCompleted;
        
        /// <remarks/>
        public event ValidateClientIDCompletedEventHandler ValidateClientIDCompleted;
        
        /// <remarks/>
        public event GetXmlCompletedEventHandler GetXmlCompleted;
        
        /// <remarks/>
        public event PropisCompletedEventHandler PropisCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://morpher.ru/GetAdjectives", RequestNamespace="http://morpher.ru/", ResponseNamespace="http://morpher.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAdjectives(string s) {
            object[] results = this.Invoke("GetAdjectives", new object[] {
                        s});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAdjectivesAsync(string s) {
            this.GetAdjectivesAsync(s, null);
        }
        
        /// <remarks/>
        public void GetAdjectivesAsync(string s, object userState) {
            if ((this.GetAdjectivesOperationCompleted == null)) {
                this.GetAdjectivesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdjectivesOperationCompleted);
            }
            this.InvokeAsync("GetAdjectives", new object[] {
                        s}, this.GetAdjectivesOperationCompleted, userState);
        }
        
        private void OnGetAdjectivesOperationCompleted(object arg) {
            if ((this.GetAdjectivesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdjectivesCompleted(this, new GetAdjectivesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://morpher.ru/SubmitCorrection", RequestNamespace="http://morpher.ru/", ResponseNamespace="http://morpher.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SubmitCorrection(GetXmlResult correction, string comment) {
            this.Invoke("SubmitCorrection", new object[] {
                        correction,
                        comment});
        }
        
        /// <remarks/>
        public void SubmitCorrectionAsync(GetXmlResult correction, string comment) {
            this.SubmitCorrectionAsync(correction, comment, null);
        }
        
        /// <remarks/>
        public void SubmitCorrectionAsync(GetXmlResult correction, string comment, object userState) {
            if ((this.SubmitCorrectionOperationCompleted == null)) {
                this.SubmitCorrectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitCorrectionOperationCompleted);
            }
            this.InvokeAsync("SubmitCorrection", new object[] {
                        correction,
                        comment}, this.SubmitCorrectionOperationCompleted, userState);
        }
        
        private void OnSubmitCorrectionOperationCompleted(object arg) {
            if ((this.SubmitCorrectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitCorrectionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://morpher.ru/GetAccountStatus", RequestNamespace="http://morpher.ru/", ResponseNamespace="http://morpher.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAccountStatus() {
            object[] results = this.Invoke("GetAccountStatus", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountStatusAsync() {
            this.GetAccountStatusAsync(null);
        }
        
        /// <remarks/>
        public void GetAccountStatusAsync(object userState) {
            if ((this.GetAccountStatusOperationCompleted == null)) {
                this.GetAccountStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountStatusOperationCompleted);
            }
            this.InvokeAsync("GetAccountStatus", new object[0], this.GetAccountStatusOperationCompleted, userState);
        }
        
        private void OnGetAccountStatusOperationCompleted(object arg) {
            if ((this.GetAccountStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountStatusCompleted(this, new GetAccountStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://morpher.ru/GetDeclension", RequestNamespace="http://morpher.ru/", ResponseNamespace="http://morpher.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetXmlResult GetDeclension(string s) {
            object[] results = this.Invoke("GetDeclension", new object[] {
                        s});
            return ((GetXmlResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetDeclensionAsync(string s) {
            this.GetDeclensionAsync(s, null);
        }
        
        /// <remarks/>
        public void GetDeclensionAsync(string s, object userState) {
            if ((this.GetDeclensionOperationCompleted == null)) {
                this.GetDeclensionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeclensionOperationCompleted);
            }
            this.InvokeAsync("GetDeclension", new object[] {
                        s}, this.GetDeclensionOperationCompleted, userState);
        }
        
        private void OnGetDeclensionOperationCompleted(object arg) {
            if ((this.GetDeclensionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeclensionCompleted(this, new GetDeclensionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://morpher.ru/GetXmlUkr", RequestNamespace="http://morpher.ru/", ResponseNamespace="http://morpher.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetXmlUkrResult GetXmlUkr(string s) {
            object[] results = this.Invoke("GetXmlUkr", new object[] {
                        s});
            return ((GetXmlUkrResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetXmlUkrAsync(string s) {
            this.GetXmlUkrAsync(s, null);
        }
        
        /// <remarks/>
        public void GetXmlUkrAsync(string s, object userState) {
            if ((this.GetXmlUkrOperationCompleted == null)) {
                this.GetXmlUkrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetXmlUkrOperationCompleted);
            }
            this.InvokeAsync("GetXmlUkr", new object[] {
                        s}, this.GetXmlUkrOperationCompleted, userState);
        }
        
        private void OnGetXmlUkrOperationCompleted(object arg) {
            if ((this.GetXmlUkrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetXmlUkrCompleted(this, new GetXmlUkrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://morpher.ru/PropisUkr", RequestNamespace="http://morpher.ru/", ResponseNamespace="http://morpher.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PropisUkrResult PropisUkr(uint n, string unit) {
            object[] results = this.Invoke("PropisUkr", new object[] {
                        n,
                        unit});
            return ((PropisUkrResult)(results[0]));
        }
        
        /// <remarks/>
        public void PropisUkrAsync(uint n, string unit) {
            this.PropisUkrAsync(n, unit, null);
        }
        
        /// <remarks/>
        public void PropisUkrAsync(uint n, string unit, object userState) {
            if ((this.PropisUkrOperationCompleted == null)) {
                this.PropisUkrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPropisUkrOperationCompleted);
            }
            this.InvokeAsync("PropisUkr", new object[] {
                        n,
                        unit}, this.PropisUkrOperationCompleted, userState);
        }
        
        private void OnPropisUkrOperationCompleted(object arg) {
            if ((this.PropisUkrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PropisUkrCompleted(this, new PropisUkrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://morpher.ru/GetDailyQueryLimit", RequestNamespace="http://morpher.ru/", ResponseNamespace="http://morpher.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetDailyQueryLimit() {
            object[] results = this.Invoke("GetDailyQueryLimit", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetDailyQueryLimitAsync() {
            this.GetDailyQueryLimitAsync(null);
        }
        
        /// <remarks/>
        public void GetDailyQueryLimitAsync(object userState) {
            if ((this.GetDailyQueryLimitOperationCompleted == null)) {
                this.GetDailyQueryLimitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDailyQueryLimitOperationCompleted);
            }
            this.InvokeAsync("GetDailyQueryLimit", new object[0], this.GetDailyQueryLimitOperationCompleted, userState);
        }
        
        private void OnGetDailyQueryLimitOperationCompleted(object arg) {
            if ((this.GetDailyQueryLimitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDailyQueryLimitCompleted(this, new GetDailyQueryLimitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://morpher.ru/ValidateClientID", RequestNamespace="http://morpher.ru/", ResponseNamespace="http://morpher.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidateClientID(string clientID) {
            object[] results = this.Invoke("ValidateClientID", new object[] {
                        clientID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateClientIDAsync(string clientID) {
            this.ValidateClientIDAsync(clientID, null);
        }
        
        /// <remarks/>
        public void ValidateClientIDAsync(string clientID, object userState) {
            if ((this.ValidateClientIDOperationCompleted == null)) {
                this.ValidateClientIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateClientIDOperationCompleted);
            }
            this.InvokeAsync("ValidateClientID", new object[] {
                        clientID}, this.ValidateClientIDOperationCompleted, userState);
        }
        
        private void OnValidateClientIDOperationCompleted(object arg) {
            if ((this.ValidateClientIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateClientIDCompleted(this, new ValidateClientIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://morpher.ru/GetXml", RequestNamespace="http://morpher.ru/", ResponseNamespace="http://morpher.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetXmlResult GetXml(string s) {
            object[] results = this.Invoke("GetXml", new object[] {
                        s});
            return ((GetXmlResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetXmlAsync(string s) {
            this.GetXmlAsync(s, null);
        }
        
        /// <remarks/>
        public void GetXmlAsync(string s, object userState) {
            if ((this.GetXmlOperationCompleted == null)) {
                this.GetXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetXmlOperationCompleted);
            }
            this.InvokeAsync("GetXml", new object[] {
                        s}, this.GetXmlOperationCompleted, userState);
        }
        
        private void OnGetXmlOperationCompleted(object arg) {
            if ((this.GetXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetXmlCompleted(this, new GetXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://morpher.ru/Propis", RequestNamespace="http://morpher.ru/", ResponseNamespace="http://morpher.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PropisResult Propis(uint n, string unit) {
            object[] results = this.Invoke("Propis", new object[] {
                        n,
                        unit});
            return ((PropisResult)(results[0]));
        }
        
        /// <remarks/>
        public void PropisAsync(uint n, string unit) {
            this.PropisAsync(n, unit, null);
        }
        
        /// <remarks/>
        public void PropisAsync(uint n, string unit, object userState) {
            if ((this.PropisOperationCompleted == null)) {
                this.PropisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPropisOperationCompleted);
            }
            this.InvokeAsync("Propis", new object[] {
                        n,
                        unit}, this.PropisOperationCompleted, userState);
        }
        
        private void OnPropisOperationCompleted(object arg) {
            if ((this.PropisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PropisCompleted(this, new PropisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://morpher.ru/", IsNullable=false)]
    public partial class Credentials : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class PropisResult {
        
        private Forms nField;
        
        private Forms unitField;
        
        /// <remarks/>
        public Forms n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        public Forms unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetXmlResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class Forms {
        
        private string иField;
        
        private string рField;
        
        private string дField;
        
        private string вField;
        
        private string тField;
        
        private string пField;
        
        private string поField;
        
        /// <remarks/>
        public string И {
            get {
                return this.иField;
            }
            set {
                this.иField = value;
            }
        }
        
        /// <remarks/>
        public string Р {
            get {
                return this.рField;
            }
            set {
                this.рField = value;
            }
        }
        
        /// <remarks/>
        public string Д {
            get {
                return this.дField;
            }
            set {
                this.дField = value;
            }
        }
        
        /// <remarks/>
        public string В {
            get {
                return this.вField;
            }
            set {
                this.вField = value;
            }
        }
        
        /// <remarks/>
        public string Т {
            get {
                return this.тField;
            }
            set {
                this.тField = value;
            }
        }
        
        /// <remarks/>
        public string П {
            get {
                return this.пField;
            }
            set {
                this.пField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("П-о")]
        public string По {
            get {
                return this.поField;
            }
            set {
                this.поField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class GetXmlResult : Forms {
        
        private string родField;
        
        private Forms множественноеField;
        
        private string гдеField;
        
        private string кудаField;
        
        private string откудаField;
        
        private ФИО фИОField;
        
        /// <remarks/>
        public string род {
            get {
                return this.родField;
            }
            set {
                this.родField = value;
            }
        }
        
        /// <remarks/>
        public Forms множественное {
            get {
                return this.множественноеField;
            }
            set {
                this.множественноеField = value;
            }
        }
        
        /// <remarks/>
        public string где {
            get {
                return this.гдеField;
            }
            set {
                this.гдеField = value;
            }
        }
        
        /// <remarks/>
        public string куда {
            get {
                return this.кудаField;
            }
            set {
                this.кудаField = value;
            }
        }
        
        /// <remarks/>
        public string откуда {
            get {
                return this.откудаField;
            }
            set {
                this.откудаField = value;
            }
        }
        
        /// <remarks/>
        public ФИО ФИО {
            get {
                return this.фИОField;
            }
            set {
                this.фИОField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class ФИО {
        
        private string фField;
        
        private string иField;
        
        private string оField;
        
        /// <remarks/>
        public string Ф {
            get {
                return this.фField;
            }
            set {
                this.фField = value;
            }
        }
        
        /// <remarks/>
        public string И {
            get {
                return this.иField;
            }
            set {
                this.иField = value;
            }
        }
        
        /// <remarks/>
        public string О {
            get {
                return this.оField;
            }
            set {
                this.оField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class PropisUkrResult {
        
        private FormsUkr nField;
        
        private FormsUkr unitField;
        
        /// <remarks/>
        public FormsUkr n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        public FormsUkr unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetXmlUkrResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class FormsUkr {
        
        private string нField;
        
        private string рField;
        
        private string дField;
        
        private string зField;
        
        private string оField;
        
        private string мField;
        
        private string кField;
        
        /// <remarks/>
        public string Н {
            get {
                return this.нField;
            }
            set {
                this.нField = value;
            }
        }
        
        /// <remarks/>
        public string Р {
            get {
                return this.рField;
            }
            set {
                this.рField = value;
            }
        }
        
        /// <remarks/>
        public string Д {
            get {
                return this.дField;
            }
            set {
                this.дField = value;
            }
        }
        
        /// <remarks/>
        public string З {
            get {
                return this.зField;
            }
            set {
                this.зField = value;
            }
        }
        
        /// <remarks/>
        public string О {
            get {
                return this.оField;
            }
            set {
                this.оField = value;
            }
        }
        
        /// <remarks/>
        public string М {
            get {
                return this.мField;
            }
            set {
                this.мField = value;
            }
        }
        
        /// <remarks/>
        public string К {
            get {
                return this.кField;
            }
            set {
                this.кField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class GetXmlUkrResult : FormsUkr {
        
        private string рідField;
        
        private Forms множинаField;
        
        /// <remarks/>
        public string рід {
            get {
                return this.рідField;
            }
            set {
                this.рідField = value;
            }
        }
        
        /// <remarks/>
        public Forms множина {
            get {
                return this.множинаField;
            }
            set {
                this.множинаField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAdjectivesCompletedEventHandler(object sender, GetAdjectivesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdjectivesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAdjectivesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SubmitCorrectionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAccountStatusCompletedEventHandler(object sender, GetAccountStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDeclensionCompletedEventHandler(object sender, GetDeclensionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeclensionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeclensionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetXmlResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetXmlResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetXmlUkrCompletedEventHandler(object sender, GetXmlUkrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetXmlUkrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetXmlUkrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetXmlUkrResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetXmlUkrResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PropisUkrCompletedEventHandler(object sender, PropisUkrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PropisUkrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PropisUkrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PropisUkrResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PropisUkrResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDailyQueryLimitCompletedEventHandler(object sender, GetDailyQueryLimitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDailyQueryLimitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDailyQueryLimitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ValidateClientIDCompletedEventHandler(object sender, ValidateClientIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateClientIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateClientIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetXmlCompletedEventHandler(object sender, GetXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetXmlResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetXmlResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PropisCompletedEventHandler(object sender, PropisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PropisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PropisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PropisResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PropisResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591